### ISSUE TITLE
Lesson 1 worksheet

### ISSUE THREAD

**Issue by KeithCarscadden** [raspberrypilearning/visualising-sorting-with-python#3]
Marc,

In Lesson 1 Worksheet, at Graphing List of Numbers, poit 5, if I enter the lines 1 by 1 into Python 3 Idle, then at plt.scatter(x,y), the plot appears. But if I enter the lines into the Idle file editor, and run from there, no plot appears unless I add either plt.ion() at the beginning and a sleep(5) at the end, or preferably plt.show() at the end.

Keith

**Comment by MarcScott** [comment]
@KeithCarscadden Thanks and should be fixed now
