### ISSUE TITLE
Lesson 1 worksheet Question

### ISSUE THREAD

**Issue by kihonkai** [raspberrypilearning/visualising-sorting-with-python#4]
I was just looking through the worksheet and plan.  I noticed List comprehensions section has this part:

> Try using list comprehensions to create the following lists:
> [10,11,12,13,14,15,16,17,18,19]
> [-5,-6,-7,-8,-9,0]

This code works for the first one:

`numbers = [i for i in range(10,20)`

I can't see how you could generate the second list based on what has been introduced so far.  Technically the sorted() function in Python can be used but the following lessons explain how a selection of sorting algorithms work.

Is this a mistake or have I missed something obvious?

**Comment by lawsie** [comment]
Paging @MarcScott on this one. Hope to get back to you soon @kihonkai

**Comment by MarcScott** [comment]
@kihonkai Fixed this now. Thanks for bringing it to our attention, and you are right, the question was impossible based on what had been taught.
